/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puzzle;

import java.awt.event.MouseListener;
import java.util.Collection;
import java.util.Collections;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Chuwi
 */
public class elJuego extends javax.swing.JFrame {

    JLabel[] piezas = new JLabel[16];
    int cont = 0;

    int positionPieza = 0;

    /**
     * Creates new form elJuego
     */
    public elJuego() {
        //this.piezas = new JLabel[]{pieza1, pieza2, pieza3, pieza4, pieza5, pieza6, pieza7, pieza8, pieza9, pieza10, pieza11, pieza12, pieza13, pieza14, pieza15, pieza16};
        initComponents();
       
        pieza1fondo.setVisible(false);
        pieza2fondo.setVisible(false);
        pieza3fondo.setVisible(false);
        pieza4fondo.setVisible(false);
        pieza5fondo.setVisible(false);
        pieza6fondo.setVisible(false);
        pieza7fondo.setVisible(false);
        pieza8fondo.setVisible(false);
        pieza9fondo.setVisible(false);
        pieza10fondo.setVisible(false);
        pieza11fondo.setVisible(false);
        pieza12fondo.setVisible(false);
        pieza13fondo.setVisible(false);
        pieza14fondo.setVisible(false);
        pieza15fondo.setVisible(false);
        pieza16fondo.setVisible(false);
        
        this.setSize(1920, 1080);
        setLocationRelativeTo(this);
        this.piezas[0] = pieza1;
        this.piezas[1] = pieza2;
        this.piezas[2] = pieza3;
        this.piezas[3] = pieza4;
        this.piezas[4] = pieza5;
        this.piezas[5] = pieza6;
        this.piezas[6] = pieza7;
        this.piezas[7] = pieza8;
        this.piezas[8] = pieza9;
        this.piezas[9] = pieza10;
        this.piezas[10] = pieza11;
        this.piezas[11] = pieza12;
        this.piezas[12] = pieza13;
        this.piezas[13] = pieza14;
        this.piezas[14] = pieza15;
        this.piezas[15] = pieza16;
        
        shuffleArray(this.piezas);
        
        this.piezas[0].setVisible(false);
        this.piezas[1].setVisible(false);
        this.piezas[2].setVisible(false);
        this.piezas[3].setVisible(false);
        this.piezas[4].setVisible(false);
        this.piezas[5].setVisible(false);
        this.piezas[6].setVisible(false);
        this.piezas[7].setVisible(false);
        this.piezas[8].setVisible(false);
        this.piezas[9].setVisible(false);
        this.piezas[10].setVisible(false);
        this.piezas[11].setVisible(false);
        this.piezas[12].setVisible(false);
        this.piezas[13].setVisible(false);
        this.piezas[14].setVisible(false);
        this.piezas[15].setVisible(false);
        aleatorios();
        // pieza1.setVisible(false);
        //pieza2.setVisible(false);
        
    }
    
    static void shuffleArray(JLabel[] ar){
        Random rn = ThreadLocalRandom.current();
        
        for (int i = ar.length - 1; i > 0; i--) {
            int index = rn.nextInt(i + 1);
            JLabel a = ar[index];
            ar[index] = ar[i];
            ar[i] = a;
        }
    }

    public void aleatorios() {
        System.out.println("ENTRA ALEATORIOS");
        //int Rango = (15 - 0) + 1;
        //int aleatorio = (int) (Math.random() * Rango + 0);
        //System.out.println(aleatorio);
        System.out.println("POSITIONPIEZA VALE: " + positionPieza);
        this.piezas[positionPieza].setVisible(true);
        positionPieza ++;
        
        System.out.println("POSITIONPIEZA VALE: " + positionPieza);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pieza1 = new javax.swing.JLabel();
        cuadrante4 = new javax.swing.JLabel();
        cuadrante2 = new javax.swing.JLabel();
        pieza2 = new javax.swing.JLabel();
        cuadrante3 = new javax.swing.JLabel();
        pieza3 = new javax.swing.JLabel();
        pieza4 = new javax.swing.JLabel();
        cuadrante5 = new javax.swing.JLabel();
        cuadrante6 = new javax.swing.JLabel();
        cuadrante7 = new javax.swing.JLabel();
        cuadrante8 = new javax.swing.JLabel();
        cuadrante9 = new javax.swing.JLabel();
        cuadrante10 = new javax.swing.JLabel();
        cuadrante12 = new javax.swing.JLabel();
        cuadrante11 = new javax.swing.JLabel();
        cuadrante13 = new javax.swing.JLabel();
        cuadrante14 = new javax.swing.JLabel();
        cuadrante15 = new javax.swing.JLabel();
        cuadrante16 = new javax.swing.JLabel();
        pieza5 = new javax.swing.JLabel();
        pieza6 = new javax.swing.JLabel();
        pieza7 = new javax.swing.JLabel();
        pieza8 = new javax.swing.JLabel();
        pieza9 = new javax.swing.JLabel();
        pieza10 = new javax.swing.JLabel();
        pieza11 = new javax.swing.JLabel();
        pieza12 = new javax.swing.JLabel();
        pieza13 = new javax.swing.JLabel();
        pieza14 = new javax.swing.JLabel();
        pieza15 = new javax.swing.JLabel();
        pieza1fondo = new javax.swing.JLabel();
        pieza16 = new javax.swing.JLabel();
        cuadrante1 = new javax.swing.JLabel();
        pieza2fondo = new javax.swing.JLabel();
        pieza3fondo = new javax.swing.JLabel();
        pieza4fondo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pieza5fondo = new javax.swing.JLabel();
        pieza6fondo = new javax.swing.JLabel();
        pieza7fondo = new javax.swing.JLabel();
        pieza8fondo = new javax.swing.JLabel();
        pieza9fondo = new javax.swing.JLabel();
        pieza10fondo = new javax.swing.JLabel();
        pieza11fondo = new javax.swing.JLabel();
        pieza12fondo = new javax.swing.JLabel();
        pieza13fondo = new javax.swing.JLabel();
        pieza14fondo = new javax.swing.JLabel();
        pieza15fondo = new javax.swing.JLabel();
        pieza16fondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pieza1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/1.jpg"))); // NOI18N
        pieza1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pieza1MouseDragged(evt);
            }
        });
        pieza1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pieza1MouseReleased(evt);
            }
        });
        getContentPane().add(pieza1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 890, -1, -1));

        cuadrante4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(cuadrante4, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 699, 289, 181));

        cuadrante2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cuadrante2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cuadrante2MouseReleased(evt);
            }
        });
        getContentPane().add(cuadrante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 282, 289, 181));

        pieza2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/2.jpg"))); // NOI18N
        pieza2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pieza2MouseDragged(evt);
            }
        });
        pieza2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pieza2MouseReleased(evt);
            }
        });
        getContentPane().add(pieza2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 880, -1, -1));

        cuadrante3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cuadrante3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cuadrante3MouseReleased(evt);
            }
        });
        getContentPane().add(cuadrante3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 489, 289, 181));

        pieza3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/3.jpg"))); // NOI18N
        pieza3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pieza3MouseDragged(evt);
            }
        });
        pieza3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pieza3MouseReleased(evt);
            }
        });
        getContentPane().add(pieza3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 550, 289, -1));

        pieza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/4.jpg"))); // NOI18N
        pieza4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pieza4MouseDragged(evt);
            }
        });
        pieza4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pieza4MouseReleased(evt);
            }
        });
        getContentPane().add(pieza4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 690, -1, -1));

        cuadrante5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cuadrante5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cuadrante5MouseReleased(evt);
            }
        });
        getContentPane().add(cuadrante5, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 75, 289, 181));

        cuadrante6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cuadrante6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cuadrante6MouseReleased(evt);
            }
        });
        getContentPane().add(cuadrante6, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 282, 289, 181));

        cuadrante7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cuadrante7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cuadrante7MouseReleased(evt);
            }
        });
        getContentPane().add(cuadrante7, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 489, 289, 181));

        cuadrante8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cuadrante8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cuadrante8MouseReleased(evt);
            }
        });
        getContentPane().add(cuadrante8, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 699, 289, 181));

        cuadrante9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cuadrante9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cuadrante9MouseReleased(evt);
            }
        });
        getContentPane().add(cuadrante9, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 75, 289, 181));

        cuadrante10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cuadrante10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cuadrante10MouseReleased(evt);
            }
        });
        getContentPane().add(cuadrante10, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 282, 289, 181));

        cuadrante12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cuadrante12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cuadrante12MouseReleased(evt);
            }
        });
        getContentPane().add(cuadrante12, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 699, 289, 181));

        cuadrante11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cuadrante11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cuadrante11MouseReleased(evt);
            }
        });
        getContentPane().add(cuadrante11, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 489, 289, 181));

        cuadrante13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cuadrante13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cuadrante13MouseReleased(evt);
            }
        });
        getContentPane().add(cuadrante13, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 75, 289, 181));

        cuadrante14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cuadrante14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cuadrante14MouseReleased(evt);
            }
        });
        getContentPane().add(cuadrante14, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 282, 289, 181));

        cuadrante15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cuadrante15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cuadrante15MouseReleased(evt);
            }
        });
        getContentPane().add(cuadrante15, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 489, 289, 181));

        cuadrante16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cuadrante16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cuadrante16MouseReleased(evt);
            }
        });
        getContentPane().add(cuadrante16, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 699, 289, 181));

        pieza5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/5.jpg"))); // NOI18N
        pieza5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pieza5MouseDragged(evt);
            }
        });
        pieza5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pieza5MouseReleased(evt);
            }
        });
        getContentPane().add(pieza5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 610, -1, -1));

        pieza6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/6.jpg"))); // NOI18N
        pieza6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pieza6MouseDragged(evt);
            }
        });
        pieza6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pieza6MouseReleased(evt);
            }
        });
        getContentPane().add(pieza6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 490, -1, -1));

        pieza7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/7.jpg"))); // NOI18N
        pieza7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pieza7MouseDragged(evt);
            }
        });
        pieza7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pieza7MouseReleased(evt);
            }
        });
        getContentPane().add(pieza7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 580, -1, -1));

        pieza8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/8.jpg"))); // NOI18N
        pieza8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pieza8MouseDragged(evt);
            }
        });
        pieza8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pieza8MouseReleased(evt);
            }
        });
        getContentPane().add(pieza8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 650, -1, -1));

        pieza9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/9.jpg"))); // NOI18N
        pieza9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pieza9MouseDragged(evt);
            }
        });
        pieza9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pieza9MouseReleased(evt);
            }
        });
        getContentPane().add(pieza9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 630, -1, -1));

        pieza10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/10.jpg"))); // NOI18N
        pieza10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pieza10MouseDragged(evt);
            }
        });
        pieza10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pieza10MouseReleased(evt);
            }
        });
        getContentPane().add(pieza10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 730, -1, -1));

        pieza11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/11.jpg"))); // NOI18N
        pieza11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pieza11MouseDragged(evt);
            }
        });
        pieza11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pieza11MouseReleased(evt);
            }
        });
        getContentPane().add(pieza11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 510, -1, -1));

        pieza12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/12.jpg"))); // NOI18N
        pieza12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pieza12MouseDragged(evt);
            }
        });
        pieza12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pieza12MouseReleased(evt);
            }
        });
        getContentPane().add(pieza12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 590, -1, -1));

        pieza13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/13.jpg"))); // NOI18N
        pieza13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pieza13MouseDragged(evt);
            }
        });
        pieza13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pieza13MouseReleased(evt);
            }
        });
        getContentPane().add(pieza13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 490, -1, -1));

        pieza14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/14.jpg"))); // NOI18N
        pieza14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pieza14MouseDragged(evt);
            }
        });
        pieza14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pieza14MouseReleased(evt);
            }
        });
        getContentPane().add(pieza14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 830, -1, -1));

        pieza15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/15.jpg"))); // NOI18N
        pieza15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pieza15MouseDragged(evt);
            }
        });
        pieza15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pieza15MouseReleased(evt);
            }
        });
        getContentPane().add(pieza15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1556, 699, -1, -1));

        pieza1fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/1.jpg"))); // NOI18N
        getContentPane().add(pieza1fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 75, 289, 181));

        pieza16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/16.jpg"))); // NOI18N
        pieza16.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pieza16MouseDragged(evt);
            }
        });
        pieza16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pieza16MouseReleased(evt);
            }
        });
        getContentPane().add(pieza16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 650, -1, -1));

        cuadrante1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(cuadrante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 75, 289, 181));

        pieza2fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/2.jpg"))); // NOI18N
        getContentPane().add(pieza2fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 282, 289, 181));

        pieza3fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/3.jpg"))); // NOI18N
        getContentPane().add(pieza3fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 489, 289, 181));

        pieza4fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/4.jpg"))); // NOI18N
        getContentPane().add(pieza4fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 699, 289, 181));

        jButton1.setText("reiniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 90, -1, -1));

        pieza5fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/5.jpg"))); // NOI18N
        getContentPane().add(pieza5fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 75, 289, 181));

        pieza6fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/6.jpg"))); // NOI18N
        getContentPane().add(pieza6fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 282, 289, 181));

        pieza7fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/7.jpg"))); // NOI18N
        getContentPane().add(pieza7fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 489, 289, 181));

        pieza8fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/8.jpg"))); // NOI18N
        getContentPane().add(pieza8fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 699, 289, 181));

        pieza9fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/9.jpg"))); // NOI18N
        getContentPane().add(pieza9fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 75, 289, 181));

        pieza10fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/10.jpg"))); // NOI18N
        getContentPane().add(pieza10fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 282, 289, 181));

        pieza11fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/11.jpg"))); // NOI18N
        pieza11fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(pieza11fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 489, 289, 181));

        pieza12fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/12.jpg"))); // NOI18N
        getContentPane().add(pieza12fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 699, 289, 181));

        pieza13fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/13.jpg"))); // NOI18N
        getContentPane().add(pieza13fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 75, 289, 181));

        pieza14fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/14.jpg"))); // NOI18N
        getContentPane().add(pieza14fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 282, 289, 181));

        pieza15fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/15.jpg"))); // NOI18N
        getContentPane().add(pieza15fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 489, 289, 181));

        pieza16fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/imagenes/16.jpg"))); // NOI18N
        getContentPane().add(pieza16fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 699, 289, 181));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle/beigefondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuadrante2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadrante2MouseReleased
        JOptionPane.showMessageDialog(null, cuadrante2.getX() + "\n" + cuadrante2.getY());
    }//GEN-LAST:event_cuadrante2MouseReleased

    private void cuadrante3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadrante3MouseReleased
        JOptionPane.showMessageDialog(null, cuadrante3.getX() + "\n" + cuadrante3.getY());
    }//GEN-LAST:event_cuadrante3MouseReleased

    private void pieza2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza2MouseDragged
        pieza2.setLocation(pieza2.getLocation().x + evt.getX() - pieza2.getWidth() / 2,
                pieza2.getLocation().y + evt.getY() - pieza2.getWidth() / 2);
    }//GEN-LAST:event_pieza2MouseDragged

    private void pieza2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza2MouseReleased
        if ((pieza2.getX() >= 75 && pieza2.getX() <= 75 + 280 && pieza2.getX() >= 75 && pieza2.getX() <= 75 + 280)
                && (pieza2.getY() >= 282 && pieza2.getY() <= 282 + 180 && pieza2.getY() >= 282 && pieza2.getY() <= 282 + 180)) {
            cont++;
            pieza2fondo.setVisible(true);
             pieza2.setVisible(false);
           if (cont<16){
                   aleatorios();
               }
            if (cont == 16) {//IGUALAR EL CONTADOR A LA CANTIDAD DE OBJETOS A MOVER
                JOptionPane.showMessageDialog(null, "F E L I C I D A D E S   H A  G A N A D O !!!");
            }
        } else {
            pieza2.setLocation(1500, 240); //ubicacion inicial del objeto
            JOptionPane.showMessageDialog(null, " I N C O R R E C T O ");
        }
    }//GEN-LAST:event_pieza2MouseReleased

    private void pieza3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza3MouseReleased
        if ((pieza3.getX() >= 75 && pieza3.getX() <= 75 + 280 && pieza3.getX() >= 75 && pieza3.getX() <= 75 + 280)
                && (pieza3.getY() >= 489 && pieza3.getY() <= 489 + 180 && pieza3.getY() >= 489 && pieza3.getY() <= 489 + 180)) {
            cont++;
            pieza3fondo.setVisible(true);
            pieza3.setVisible(false);
            if (cont<16){
                   aleatorios();
               }
            if (cont == 16) {//IGUALAR EL CONTADOR A LA CANTIDAD DE OBJETOS A MOVER
                JOptionPane.showMessageDialog(null, "F E L I C I D A D E S   H A  G A N A D O !!!");
            }
        } else {
            pieza3.setLocation(1500, 240); //ubicacion inicial del objeto
            JOptionPane.showMessageDialog(null, " I N C O R R E C T O ");
        }
    }//GEN-LAST:event_pieza3MouseReleased

    private void pieza3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza3MouseDragged
        pieza3.setLocation(pieza3.getLocation().x + evt.getX() - pieza3.getWidth() / 2,
                pieza3.getLocation().y + evt.getY() - pieza3.getWidth() / 2);
    }//GEN-LAST:event_pieza3MouseDragged

    private void pieza4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza4MouseDragged
        pieza4.setLocation(pieza4.getLocation().x + evt.getX() - pieza4.getWidth() / 2,
                pieza4.getLocation().y + evt.getY() - pieza4.getWidth() / 2);
    }//GEN-LAST:event_pieza4MouseDragged

    private void pieza4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza4MouseReleased
        if ((pieza4.getX() >= 75 && pieza4.getX() <= 75 + 280 && pieza4.getX() >= 75 && pieza4.getX() <= 75 + 280)
                && (pieza4.getY() >= 699 && pieza4.getY() <= 699 + 180 && pieza4.getY() >= 699 && pieza4.getY() <= 699 + 180)) {
            cont++;
            if (cont<16){
                   aleatorios();
               }
            pieza4fondo.setVisible(true);
            pieza4.setVisible(false);
            if (cont == 16) {//IGUALAR EL CONTADOR A LA CANTIDAD DE OBJETOS A MOVER
                JOptionPane.showMessageDialog(null, "F E L I C I D A D E S   H A  G A N A D O !!!");
            }
        } else {
            pieza4.setLocation(1500, 240); //ubicacion inicial del objeto
            JOptionPane.showMessageDialog(null, " I N C O R R E C T O ");
        }
    }//GEN-LAST:event_pieza4MouseReleased

    private void cuadrante5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadrante5MouseReleased
        JOptionPane.showMessageDialog(null, cuadrante5.getX() + "\n" + cuadrante5.getY());
    }//GEN-LAST:event_cuadrante5MouseReleased

    private void cuadrante6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadrante6MouseReleased
        JOptionPane.showMessageDialog(null, cuadrante6.getX() + "\n" + cuadrante6.getY());
    }//GEN-LAST:event_cuadrante6MouseReleased

    private void cuadrante7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadrante7MouseReleased
        JOptionPane.showMessageDialog(null, cuadrante7.getX() + "\n" + cuadrante7.getY());
    }//GEN-LAST:event_cuadrante7MouseReleased

    private void cuadrante8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadrante8MouseReleased
        JOptionPane.showMessageDialog(null, cuadrante8.getX() + "\n" + cuadrante8.getY());
    }//GEN-LAST:event_cuadrante8MouseReleased

    private void cuadrante9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadrante9MouseReleased
        JOptionPane.showMessageDialog(null, cuadrante9.getX() + "\n" + cuadrante9.getY());
    }//GEN-LAST:event_cuadrante9MouseReleased

    private void cuadrante10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadrante10MouseReleased
        JOptionPane.showMessageDialog(null, cuadrante10.getX() + "\n" + cuadrante10.getY());
    }//GEN-LAST:event_cuadrante10MouseReleased

    private void cuadrante12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadrante12MouseReleased
        JOptionPane.showMessageDialog(null, cuadrante12.getX() + "\n" + cuadrante12.getY());
    }//GEN-LAST:event_cuadrante12MouseReleased

    private void cuadrante11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadrante11MouseReleased
        JOptionPane.showMessageDialog(null, cuadrante11.getX() + "\n" + cuadrante11.getY());
    }//GEN-LAST:event_cuadrante11MouseReleased

    private void cuadrante13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadrante13MouseReleased
        JOptionPane.showMessageDialog(null, cuadrante13.getX() + "\n" + cuadrante13.getY());
    }//GEN-LAST:event_cuadrante13MouseReleased

    private void cuadrante14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadrante14MouseReleased
        JOptionPane.showMessageDialog(null, cuadrante14.getX() + "\n" + cuadrante14.getY());
    }//GEN-LAST:event_cuadrante14MouseReleased

    private void cuadrante15MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadrante15MouseReleased
        JOptionPane.showMessageDialog(null, cuadrante15.getX() + "\n" + cuadrante15.getY());
    }//GEN-LAST:event_cuadrante15MouseReleased

    private void cuadrante16MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadrante16MouseReleased
        JOptionPane.showMessageDialog(null, cuadrante16.getX() + "\n" + cuadrante16.getY());
    }//GEN-LAST:event_cuadrante16MouseReleased

    private void pieza5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza5MouseDragged
        pieza5.setLocation(pieza5.getLocation().x + evt.getX() - pieza5.getWidth() / 2,
                pieza5.getLocation().y + evt.getY() - pieza5.getWidth() / 2);
    }//GEN-LAST:event_pieza5MouseDragged

    private void pieza5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza5MouseReleased
        if ((pieza5.getX() >= 374 && pieza5.getX() <= 374 + 280 && pieza5.getX() >= 374 && pieza5.getX() <= 374 + 280)
                && (pieza5.getY() >= 75 && pieza5.getY() <= 75 + 180 && pieza5.getY() >= 75 && pieza5.getY() <= 75 + 180)) {
            cont++;
            pieza5fondo.setVisible(true);
             pieza5.setVisible(false);
            if (cont<16){
                   aleatorios();
               }
            if (cont == 16) {//IGUALAR EL CONTADOR A LA CANTIDAD DE OBJETOS A MOVER
                JOptionPane.showMessageDialog(null, "F E L I C I D A D E S   H A  G A N A D O !!!");
            }
        } else {
            pieza5.setLocation(1500, 240); //ubicacion inicial del objeto
            JOptionPane.showMessageDialog(null, " I N C O R R E C T O ");
        }
    }//GEN-LAST:event_pieza5MouseReleased

    private void pieza6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza6MouseDragged
        pieza6.setLocation(pieza6.getLocation().x + evt.getX() - pieza6.getWidth() / 2,
                pieza6.getLocation().y + evt.getY() - pieza6.getWidth() / 2);
    }//GEN-LAST:event_pieza6MouseDragged

    private void pieza6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza6MouseReleased
        if ((pieza6.getX() >= 374 && pieza6.getX() <= 75 + 374 && pieza6.getX() >= 374 && pieza6.getX() <= 374 + 280)
                && (pieza6.getY() >= 282 && pieza6.getY() <= 282 + 180 && pieza6.getY() >= 282 && pieza6.getY() <= 282 + 180)) {
            cont++;
             pieza6fondo.setVisible(true);
             pieza6.setVisible(false);
            if (cont<16){
                   aleatorios();
               }
            if (cont == 16) {//IGUALAR EL CONTADOR A LA CANTIDAD DE OBJETOS A MOVER
                JOptionPane.showMessageDialog(null, "F E L I C I D A D E S   H A  G A N A D O !!!");
            }
        } else {
            pieza6.setLocation(1500, 240); //ubicacion inicial del objeto
            JOptionPane.showMessageDialog(null, " I N C O R R E C T O ");
        }
    }//GEN-LAST:event_pieza6MouseReleased

    private void pieza7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza7MouseDragged
        pieza7.setLocation(pieza7.getLocation().x + evt.getX() - pieza7.getWidth() / 2,
                pieza7.getLocation().y + evt.getY() - pieza7.getWidth() / 2);
    }//GEN-LAST:event_pieza7MouseDragged

    private void pieza7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza7MouseReleased
        if ((pieza7.getX() >= 374 && pieza7.getX() <= 75 + 374 && pieza7.getX() >= 374 && pieza7.getX() <= 374 + 280)
                && (pieza7.getY() >= 489 && pieza7.getY() <= 489 + 180 && pieza7.getY() >= 489 && pieza7.getY() <= 489 + 180)) {
            cont++;
             pieza7fondo.setVisible(true);
             pieza7.setVisible(false);
            if (cont<16){
                   aleatorios();
               }
            if (cont == 16) {//IGUALAR EL CONTADOR A LA CANTIDAD DE OBJETOS A MOVER
                JOptionPane.showMessageDialog(null, "F E L I C I D A D E S   H A  G A N A D O !!!");
            }
        } else {
            pieza7.setLocation(1500, 240); //ubicacion inicial del objeto
            JOptionPane.showMessageDialog(null, " I N C O R R E C T O ");
        }
    }//GEN-LAST:event_pieza7MouseReleased

    private void pieza8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza8MouseDragged
        pieza8.setLocation(pieza8.getLocation().x + evt.getX() - pieza8.getWidth() / 2,
                pieza8.getLocation().y + evt.getY() - pieza8.getWidth() / 2);
    }//GEN-LAST:event_pieza8MouseDragged

    private void pieza8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza8MouseReleased
        if ((pieza8.getX() >= 374 && pieza8.getX() <= 75 + 374 && pieza8.getX() >= 374 && pieza8.getX() <= 374 + 280)
                && (pieza8.getY() >= 699 && pieza8.getY() <= 669 + 180 && pieza8.getY() >= 669 && pieza8.getY() <= 669 + 180)) {
            cont++;
             pieza8fondo.setVisible(true);
             pieza8.setVisible(false);
            if (cont<16){
                   aleatorios();
               }
            if (cont == 16) {//IGUALAR EL CONTADOR A LA CANTIDAD DE OBJETOS A MOVER
                JOptionPane.showMessageDialog(null, "F E L I C I D A D E S   H A  G A N A D O !!!");
            }
        } else {
            pieza8.setLocation(1500, 240); //ubicacion inicial del objeto
            JOptionPane.showMessageDialog(null, " I N C O R R E C T O ");
        }
    }//GEN-LAST:event_pieza8MouseReleased

    private void pieza9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza9MouseDragged
        pieza9.setLocation(pieza9.getLocation().x + evt.getX() - pieza9.getWidth() / 2,
                pieza9.getLocation().y + evt.getY() - pieza9.getWidth() / 2);
    }//GEN-LAST:event_pieza9MouseDragged

    private void pieza9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza9MouseReleased
        if ((pieza9.getX() >= 672 && pieza9.getX() <= 672 + 374 && pieza9.getX() >= 672 && pieza9.getX() <= 672 + 280)
                && (pieza9.getY() >= 75 && pieza9.getY() <= 75 + 180 && pieza9.getY() >= 75 && pieza9.getY() <= 75 + 180)) {
            cont++;
             pieza9fondo.setVisible(true);
             pieza9.setVisible(false);
            if (cont<16){
                   aleatorios();
               }
            if (cont == 16) {//IGUALAR EL CONTADOR A LA CANTIDAD DE OBJETOS A MOVER
                JOptionPane.showMessageDialog(null, "F E L I C I D A D E S   H A  G A N A D O !!!");
            }
        } else {
            pieza9.setLocation(1500, 240); //ubicacion inicial del objeto
            JOptionPane.showMessageDialog(null, " I N C O R R E C T O ");
        }
    }//GEN-LAST:event_pieza9MouseReleased

    private void pieza10MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza10MouseDragged
        pieza10.setLocation(pieza10.getLocation().x + evt.getX() - pieza10.getWidth() / 2,
                pieza10.getLocation().y + evt.getY() - pieza10.getWidth() / 2);
    }//GEN-LAST:event_pieza10MouseDragged

    private void pieza10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza10MouseReleased
        if ((pieza10.getX() >= 672 && pieza10.getX() <= 672 + 374 && pieza10.getX() >= 672 && pieza10.getX() <= 672 + 280)
                && (pieza10.getY() >= 282 && pieza10.getY() <= 282 + 180 && pieza10.getY() >= 282 && pieza10.getY() <= 282 + 180)) {
            cont++;
             pieza10fondo.setVisible(true);
             pieza10.setVisible(false);
            if (cont<16){
                   aleatorios();
               }
            if (cont == 16) {//IGUALAR EL CONTADOR A LA CANTIDAD DE OBJETOS A MOVER
                JOptionPane.showMessageDialog(null, "F E L I C I D A D E S   H A  G A N A D O !!!");
            }
        } else {
            pieza10.setLocation(1500, 240); //ubicacion inicial del objeto
            JOptionPane.showMessageDialog(null, " I N C O R R E C T O ");
        }
    }//GEN-LAST:event_pieza10MouseReleased

    private void pieza11MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza11MouseDragged
        pieza11.setLocation(pieza11.getLocation().x + evt.getX() - pieza11.getWidth() / 2,
                pieza11.getLocation().y + evt.getY() - pieza11.getWidth() / 2);
    }//GEN-LAST:event_pieza11MouseDragged

    private void pieza11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza11MouseReleased
        if ((pieza11.getX() >= 672 && pieza11.getX() <= 672 + 374 && pieza11.getX() >= 672 && pieza11.getX() <= 672 + 280)
                && (pieza11.getY() >= 489 && pieza11.getY() <= 489 + 180 && pieza11.getY() >= 489 && pieza11.getY() <= 489 + 180)) {
            cont++;
             pieza11fondo.setVisible(true);
             pieza11.setVisible(false);
            if (cont<16){
                   aleatorios();
               }
            if (cont == 16) {//IGUALAR EL CONTADOR A LA CANTIDAD DE OBJETOS A MOVER
                JOptionPane.showMessageDialog(null, "F E L I C I D A D E S   H A  G A N A D O !!!");
            }
        } else {
            pieza11.setLocation(1500, 240); //ubicacion inicial del objeto
            JOptionPane.showMessageDialog(null, " I N C O R R E C T O ");
        }
    }//GEN-LAST:event_pieza11MouseReleased

    private void pieza12MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza12MouseDragged
        pieza12.setLocation(pieza12.getLocation().x + evt.getX() - pieza12.getWidth() / 2,
                pieza12.getLocation().y + evt.getY() - pieza12.getWidth() / 2);
    }//GEN-LAST:event_pieza12MouseDragged

    private void pieza12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza12MouseReleased
        if ((pieza12.getX() >= 672 && pieza12.getX() <= 672 + 374 && pieza12.getX() >= 672 && pieza12.getX() <= 672 + 280)
                && (pieza12.getY() >= 669 && pieza12.getY() <= 669 + 180 && pieza12.getY() >= 669 && pieza12.getY() <= 669 + 180)) {
            cont++;
            pieza12fondo.setVisible(true);
            pieza12.setVisible(false);
            if (cont<16){
                   aleatorios();
               }
            if (cont == 16) {//IGUALAR EL CONTADOR A LA CANTIDAD DE OBJETOS A MOVER
                JOptionPane.showMessageDialog(null, "F E L I C I D A D E S   H A  G A N A D O !!!");
            }
        } else {
            pieza12.setLocation(1500, 240); //ubicacion inicial del objeto
            JOptionPane.showMessageDialog(null, " I N C O R R E C T O ");
        }
    }//GEN-LAST:event_pieza12MouseReleased

    private void pieza13MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza13MouseDragged
        pieza13.setLocation(pieza13.getLocation().x + evt.getX() - pieza13.getWidth() / 2,
                pieza13.getLocation().y + evt.getY() - pieza13.getWidth() / 2);
    }//GEN-LAST:event_pieza13MouseDragged

    private void pieza13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza13MouseReleased
        if ((pieza13.getX() >= 970 && pieza13.getX() <= 970 + 374 && pieza13.getX() >= 970 && pieza13.getX() <= 970 + 280)
                && (pieza13.getY() >= 75 && pieza13.getY() <= 75 + 180 && pieza13.getY() >= 75 && pieza13.getY() <= 75 + 180)) {
            cont++;
            pieza13fondo.setVisible(true);
            pieza13.setVisible(false);
            if (cont<16){
                   aleatorios();
               }
            if (cont == 16) {//IGUALAR EL CONTADOR A LA CANTIDAD DE OBJETOS A MOVER
                JOptionPane.showMessageDialog(null, "F E L I C I D A D E S   H A  G A N A D O !!!");
            }
        } else {
            pieza13.setLocation(1500, 240); //ubicacion inicial del objeto
            JOptionPane.showMessageDialog(null, " I N C O R R E C T O ");
        }
    }//GEN-LAST:event_pieza13MouseReleased

    private void pieza14MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza14MouseDragged
        pieza14.setLocation(pieza14.getLocation().x + evt.getX() - pieza14.getWidth() / 2,
                pieza14.getLocation().y + evt.getY() - pieza14.getWidth() / 2);
    }//GEN-LAST:event_pieza14MouseDragged

    private void pieza14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza14MouseReleased
        if ((pieza14.getX() >= 970 && pieza14.getX() <= 970 + 374 && pieza14.getX() >= 970 && pieza14.getX() <= 970 + 280)
                && (pieza14.getY() >= 282 && pieza14.getY() <= 282 + 180 && pieza14.getY() >= 282 && pieza14.getY() <= 282 + 180)) {
            cont++;
            pieza14fondo.setVisible(true);
            pieza14.setVisible(false);
           if (cont<16){
                   aleatorios();
               }
            if (cont == 16) {//IGUALAR EL CONTADOR A LA CANTIDAD DE OBJETOS A MOVER
                JOptionPane.showMessageDialog(null, "F E L I C I D A D E S   H A  G A N A D O !!!");
            }
        } else {
            pieza14.setLocation(1500, 240); //ubicacion inicial del objeto
            JOptionPane.showMessageDialog(null, " I N C O R R E C T O ");
        }
    }//GEN-LAST:event_pieza14MouseReleased

    private void pieza15MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza15MouseDragged
        pieza15.setLocation(pieza15.getLocation().x + evt.getX() - pieza15.getWidth() / 2,
                pieza15.getLocation().y + evt.getY() - pieza15.getWidth() / 2);
    }//GEN-LAST:event_pieza15MouseDragged

    private void pieza15MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza15MouseReleased
        if ((pieza15.getX() >= 970 && pieza15.getX() <= 970 + 374 && pieza15.getX() >= 970 && pieza15.getX() <= 970 + 280)
                && (pieza15.getY() >= 489 && pieza15.getY() <= 489 + 180 && pieza15.getY() >= 489 && pieza15.getY() <= 489 + 180)) {
            cont++;
            pieza15fondo.setVisible(true);
            pieza15.setVisible(false);
            
            if (cont<16){
                   aleatorios();
               }
            if (cont == 16) {//IGUALAR EL CONTADOR A LA CANTIDAD DE OBJETOS A MOVER
                JOptionPane.showMessageDialog(null, "F E L I C I D A D E S   H A  G A N A D O !!!");
            }
        } else {
            pieza15.setLocation(1500, 240); //ubicacion inicial del objeto
            JOptionPane.showMessageDialog(null, " I N C O R R E C T O ");
        }
    }//GEN-LAST:event_pieza15MouseReleased

    private void pieza16MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza16MouseDragged
        pieza16.setLocation(pieza16.getLocation().x + evt.getX() - pieza16.getWidth() / 2,
                pieza16.getLocation().y + evt.getY() - pieza16.getWidth() / 2);
    }//GEN-LAST:event_pieza16MouseDragged

    private void pieza16MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza16MouseReleased
        if ((pieza16.getX() >= 970 && pieza16.getX() <= 970 + 374 && pieza16.getX() >= 970 && pieza16.getX() <= 970 + 280)
                && (pieza16.getY() >= 669 && pieza16.getY() <= 669 + 180 && pieza16.getY() >= 669 && pieza16.getY() <= 669 + 180)) {
            cont++;
            pieza16fondo.setVisible(true);
            pieza16.setVisible(false);
            if (cont<16){
                   aleatorios();
               }
            if (cont == 16) {//IGUALAR EL CONTADOR A LA CANTIDAD DE OBJETOS A MOVER
                JOptionPane.showMessageDialog(null, "F E L I C I D A D E S   H A  G A N A D O !!!");
            }
        } else {
            pieza16.setLocation(1500, 240); //ubicacion inicial del objeto
            JOptionPane.showMessageDialog(null, " I N C O R R E C T O ");
        }
    }//GEN-LAST:event_pieza16MouseReleased

    private void pieza1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza1MouseReleased
        if ((pieza1.getX() >= 75 && pieza1.getX() <= 75 + 280 && pieza1.getX() >= 75 && pieza1.getX() <= 75 + 280)
            && (pieza1.getY() >= 74 && pieza1.getY() <= 74 + 180 && pieza1.getY() >= 74 && pieza1.getY() <= 74 + 180)) {
            // aleatorios();
            cont++;
            pieza1.setVisible(false);
            pieza1fondo.setVisible(true);
               pieza1.setLocation(75, 74);
               
               if (cont<16){
                   aleatorios();
               }

              
            if (cont == 16) {//IGUALAR EL CONTADOR A LA CANTIDAD DE OBJETOS A MOVER
                JOptionPane.showMessageDialog(null, "F E L I C I D A D E S   H A  G A N A D O !!!");
            }
        } else {
            pieza1.setLocation(1500, 240); //ubicacion inicial del objeto
            JOptionPane.showMessageDialog(null, " I N C O R R E C T O ");
        }

        //  JOptionPane.showMessageDialog(null, pieza1.getX()+"\n"+pieza1.getY());

    }//GEN-LAST:event_pieza1MouseReleased

    private void pieza1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieza1MouseDragged
        pieza1.setLocation(pieza1.getLocation().x + evt.getX() - pieza1.getWidth() / 2,
            pieza1.getLocation().y + evt.getY() - pieza1.getWidth() / 2);

        //JOptionPane.showMessageDialog(null, pieza1.getX()+"\n"+pieza1.getY());
    }//GEN-LAST:event_pieza1MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
       elJuego e = new elJuego();
       e.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(elJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(elJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(elJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(elJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new elJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cuadrante1;
    private javax.swing.JLabel cuadrante10;
    private javax.swing.JLabel cuadrante11;
    private javax.swing.JLabel cuadrante12;
    private javax.swing.JLabel cuadrante13;
    private javax.swing.JLabel cuadrante14;
    private javax.swing.JLabel cuadrante15;
    private javax.swing.JLabel cuadrante16;
    private javax.swing.JLabel cuadrante2;
    private javax.swing.JLabel cuadrante3;
    private javax.swing.JLabel cuadrante4;
    private javax.swing.JLabel cuadrante5;
    private javax.swing.JLabel cuadrante6;
    private javax.swing.JLabel cuadrante7;
    private javax.swing.JLabel cuadrante8;
    private javax.swing.JLabel cuadrante9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pieza1;
    private javax.swing.JLabel pieza10;
    private javax.swing.JLabel pieza10fondo;
    private javax.swing.JLabel pieza11;
    private javax.swing.JLabel pieza11fondo;
    private javax.swing.JLabel pieza12;
    private javax.swing.JLabel pieza12fondo;
    private javax.swing.JLabel pieza13;
    private javax.swing.JLabel pieza13fondo;
    private javax.swing.JLabel pieza14;
    private javax.swing.JLabel pieza14fondo;
    private javax.swing.JLabel pieza15;
    private javax.swing.JLabel pieza15fondo;
    private javax.swing.JLabel pieza16;
    private javax.swing.JLabel pieza16fondo;
    private javax.swing.JLabel pieza1fondo;
    private javax.swing.JLabel pieza2;
    private javax.swing.JLabel pieza2fondo;
    private javax.swing.JLabel pieza3;
    private javax.swing.JLabel pieza3fondo;
    private javax.swing.JLabel pieza4;
    private javax.swing.JLabel pieza4fondo;
    private javax.swing.JLabel pieza5;
    private javax.swing.JLabel pieza5fondo;
    private javax.swing.JLabel pieza6;
    private javax.swing.JLabel pieza6fondo;
    private javax.swing.JLabel pieza7;
    private javax.swing.JLabel pieza7fondo;
    private javax.swing.JLabel pieza8;
    private javax.swing.JLabel pieza8fondo;
    private javax.swing.JLabel pieza9;
    private javax.swing.JLabel pieza9fondo;
    // End of variables declaration//GEN-END:variables
}
